upstream fastcgi_backend {
    server phpfpm:9000;
}

map $request_method $cors_method {
    OPTIONS 204;
    default 0;
}

server {
    listen 80;
    server_name loom-magento.test;
    set $MAGE_ROOT /var/www/html;
    set $MAGE_MODE developer;

    add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Content-Type, Authorization' always;

    if ($request_method = 'OPTIONS') {
        return 204;
    }

    include /etc/nginx/magento.conf;
}